### ISSUE TITLE
Ansible fails at yarn dependencies

### ISSUE THREAD

**Issue by corv89** [omisego/goban#8]
# Subject of the issue

`bin/bootstrap` and `vagrant provision` fail at _TASK [ewallet : install yarn dependencies]_

# Your environment

MacOS 10.13.3

> Bootstrapping with the following configurations:
>   VAGRANT_PROVIDER: virtualbox
> 
> Performing preflight checks:
>   ✓ CLI tools is already installed.
>   ✓ Homebrew is already installed.
>   ✓ Ansible is already installed
>   ✓ Vagrant is already installed.
>   ✓ VirtualBox is already installed.
> 
> Cloning repositories:
>   ✓ ewallet is already cloned.

# Steps to reproduce

Run `vagrant provision` or
`vagrant destroy` followed by `vagrant provision`

`bin/bootstrap -r` has no effect on the outcome.

Only postgresql docker container is brought up and accessible thru port 5432

# Expected behavior

Expecting ansible to successfully install the ewallet in addition to postgresql

# Actual behavior

> TASK [ewallet : install yarn dependencies] *************************************
> fatal: [ewallet]: FAILED! => {"msg": "The conditional check ''Already up-to-date' not in yarn_result.stdout' failed. The error was: error while evaluating conditional ('Already up-to-date' not in yarn_result.stdout): Unable to look up a name or access an attribute in template string ({% if 'Already up-to-date' not in yarn_result.stdout %} True {% else %} False {% endif %}).\nMake sure your variable name does not contain invalid characters like '-': argument of type 'StrictUndefined' is not iterable"}
> 	to retry, use: --limit @/Users/corv/WebstormProjects/goban/provisioning/playbook.retry
> 
> PLAY RECAP *********************************************************************
> ewallet                    : ok=34   changed=0    unreachable=0    failed=1
> 
> Ansible failed to complete successfully. Any error output should be
> visible above. Please fix these errors and try again.

Ansible appears to be attempting to install `/vagrant/apps/admin_panel/assets` thru `ewallet.yml`, a directory which does not exist.

**Comment by unnawut** [comment]
Hi @corv89, thanks for reporting!

Just need some more information. Did you clone the `ewallet` repo from a specific branch? It seems that the `ewallet` your Goban is working is from an [pending PR](https://github.com/omisego/ewallet/pull/77/files).

**Comment by corv89** [comment]
I used the defaults and did not specify a specific branch

**Comment by corv89** [comment]
The merge you made fixed the issue after running `git pull` inside the VM. Thank you for the quick fix.
